name: 3-Terraform_new_action2

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.0

    - name: Terraform Format
      run: terraform fmt -check -recursive  # You can include `-recursive` if needed for multi-directory

    - name: Terraform Init
      run: terraform init -input=false
      working-directory: 1-Creating_storage

    - name: Terraform Validate
      run: terraform validate
      working-directory: 1-Creating_storage

    - name: Terraform Plan
      run: terraform plan -lock=false
      working-directory: 1-Creating_storage

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      working-directory: 1-Creating_storage
